name 'web'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures Apache'
long_description 'Installs/Configures Apache'
version '0.1.0'

supports 'centos'
supports 'ubuntu'
